import { i18n } from '../boot/i18n';

const { t } = i18n.global;
import { Contact } from './models';
// const { t } = useI18n();
export const columns = [
  {
    name: 'id',
    required: true,
    label: t('listLabels[0]'),
    align: 'left',
    field: (row: Contact) => row.id,
    format: (val: unknown) => `${val}`,
    sortable: true,
  },
  {
    name: 'first_name',
    required: true,
    label: t('listLabels[1]'),
    align: 'left',
    field: (row: Contact) => row.first_name,
    format: (val: unknown) => `${val}`,
    sortable: true,
  },
  {
    name: 'last_name',
    required: true,
    label: t('listLabels[2]'),
    align: 'left',
    field: (row: Contact) => row.last_name,
    format: (val: unknown) => `${val}`,
    sortable: true,
  },
  {
    name: 'company',
    required: false,
    label: t('listLabels[3]'),
    align: 'left',
    field: (row: Contact) => row.company ? row.company.name : '',
    format: (val: unknown) => `${val}`,
    sortable: true,
  },
  {
    name: 'address',
    required: false,
    label: t('listLabels[4]'),
    align: 'left',
    field: (row: Contact) => row.address,
    format: (val: unknown) => `${val}`,
    sortable: false,
  },
  {
    name: 'phone',
    required: false,
    label: t('listLabels[5]'),
    align: 'left',
    field: (row: Contact) => row.phone,
    format: (val: unknown) => `${val}`,
    sortable: false,
  },
  {
    name: 'email',
    required: false,
    label: t('listLabels[6]'),
    align: 'left',
    field: (row: Contact) => row.email,
    format: (val: unknown) => `${val}`,
    sortable: true,
  },
  {
    name: 'emergency_name',
    required: false,
    label: t('listLabels[7]'),
    align: 'left',
    field: (row: Contact) => row.emergency_name,
    format: (val: unknown) => `${val}`,
    sortable: false,
  },
  {
    name: 'emergency_phone',
    required: false,
    label: t('listLabels[8]'),
    align: 'left',
    field: (row: Contact) => row.emergency_phone,
    format: (val: unknown) => `${val}`,
    sortable: false,
  },
  {
    name: 'supervisor',
    required: false,
    label: t('listLabels[9]'),
    align: 'left',
    field: (row: Contact) => row.supervisor && row.supervisor.contact ? `${row.supervisor.contact.first_name} ${row.supervisor.contact.last_name}` : '_',
    format: (val: unknown) => `${val}`,
    sortable: true,
  },
];

export const visibleColumns = [
  // 'id',
  // 'first_name',
  // 'middle_name',
  // 'last_name',
  // 'category',
  // 'location',
  // 'phone',
  'company',
  'mobile',
  'email',
];
